---
title: "Case Study"
author: "Jasmine Zhang"
date: "2023-10-10"
output: html_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
data(nyc_airbnb)
```

```{r}
nyc_airbnb =
  nyc_airbnb |> 
  rename(borough = neighbourhood_group) |> 
  mutate(stars = review_scores_location/2)
```

## Where are AirBNBs expensive?
```{r}
nyc_airbnb |> 
  count(borough)

nyc_airbnb |> 
  group_by(borough, room_type) |> 
  summarize(median_price = median(price)) |> 
  pivot_wider(
    names_from = room_type,
    values_from = median_price
  )
```

```{r}
nyc_airbnb |> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(borough~room_type)
#Some modification
nyc_airbnb |> 
  filter(price<1000, room_type=="Entire home/apt") |>  
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(.~borough)
```
```{r}
#Where in manhattan are apt expensive
nyc_airbnb |> 
  filter(price < 1000,
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  group_by(neighbourhood) |> 
  summarize(
    n_apt = n(),
    mean_price = mean(price)) |> 
  arrange(desc(mean_price))
```
```{r}
nyc_airbnb |> 
  filter(price < 1000,
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = price, y = neighbourhood)) +
  geom_density_ridges()
```

## Make a map
```{r}
nyc_airbnb |> 
  filter(price < 1000,
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

```{r}
library(leaflet)
```


```{r}
nyc_airbnb |> 
  filter(price < 1000,
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  sample_n(30) |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~long, ~lat, radius = 0.2)
```

