---
title: "Visualization I"
output: html_document
date: "2023-09-29"
---

```{r setup}
library(tidyverse)
library(ggridges)
```

# Data loading
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
# Basic plot
```{r}
#Scatterplot
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
#use geom_hex() when data size much larger
#Use pipe to plot
weather_df |>
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

```
# Advanced plots
```{r}
ggplot(weather_df, aes(x=tmin, y=tmax))+
  geom_point(aes(color=name),alpha=0.3)+ #only points colored by name not the smooth line
  #alpha: transparent dots
  geom_smooth(se = FALSE) #get rid of error bars at the beginning

#facets
ggplot(weather_df, aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=0.3)+
  geom_smooth()+
  facet_grid(.~name)
```
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size=prcp),alpha=0.3)+
  geom_smooth()+
  facet_grid(.~name)

weather_df |> 
  filter(name=="CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) |> 
  ggplot(aes(x=tmin_fahr, y=tmax_fahr))+
  geom_point(alpha=0.3)+
  geom_smooth()
```
# Univariate plotting
```{r}
ggplot(weather_df,aes(x=tmax, fill=name))+
  geom_histogram(position = "dodge") #dodge is not stacking columns

#density plot
ggplot(weather_df,aes(x=tmax, fill=name))+
  geom_density(alpha=0.3)

#box plot
ggplot(weather_df,aes(y=tmax, x=name))+
  geom_boxplot()

#violin plot: reverse of density plot
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")
#ridge plot: seperate density plots 
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```
# Saving and embedding plots
```{r}
ggp_weather = weather_df |> 
  ggplot(aes(x=tmin,y=tmax)) + 
  geom_point()

ggsave("./ggp_weather.pdf",ggp_weather)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

